let one = document.getElementById("elzero");
console.log(one);
let two = document.getElementsByTagName("div");
console.log(two);
let three = document.getElementsByClassName("element");
console.log(three);
let four = document.getElementsByName("js");
console.log(four);
let five = document.querySelector(".element");
console.log(five);
let six = document.querySelector("#elzero");
console.log(six);
let seven = document.querySelector("div");
console.log(seven);
let eghit = document.querySelectorAll("div");
console.log(eghit);
let nine = document.querySelectorAll(".element");
console.log(nine);
let ten = document.querySelectorAll("#elzero");
console.log(ten);
